import React from 'react';
import { SectionId, NavItem } from '../types';
import { BarChart2, CreditCard, Terminal, Settings, Rocket } from 'lucide-react';

interface SidebarProps {
  currentSection: SectionId;
  onNavigate: (id: SectionId) => void;
}

const navItems: NavItem[] = [
  { id: SectionId.Overview, label: 'Ecosystem Overview', icon: BarChart2 },
  { id: SectionId.Plans, label: 'Monthly Coding Plans', icon: CreditCard },
  { id: SectionId.Cli, label: 'CLI Environments', icon: Terminal },
  { id: SectionId.Setup, label: 'Setup & Optimization', icon: Settings },
  { id: SectionId.Deployment, label: 'z.ai & Full Stack', icon: Rocket },
];

const Sidebar: React.FC<SidebarProps> = ({ currentSection, onNavigate }) => {
  return (
    <aside className="w-64 bg-white border-r border-stone-200 hidden md:flex flex-col h-full flex-shrink-0">
      <div className="p-6 border-b border-stone-100">
        <h1 className="text-2xl font-bold tracking-tight text-stone-900">
          GLM 4.7 
          <span className="text-stone-500 text-sm block font-normal mt-1">Research Report</span>
        </h1>
      </div>
      <nav className="flex-1 overflow-y-auto py-4">
        <ul className="space-y-1">
          {navItems.map((item) => {
            const isActive = currentSection === item.id;
            return (
              <li key={item.id}>
                <button
                  onClick={() => onNavigate(item.id)}
                  className={`w-full text-left px-6 py-3 flex items-center transition-colors ${
                    isActive 
                      ? 'bg-stone-100 text-stone-900 font-semibold border-l-4 border-stone-700' 
                      : 'text-stone-600 hover:bg-stone-50 hover:text-stone-900 border-l-4 border-transparent'
                  }`}
                >
                  <item.icon size={18} className={`mr-3 ${isActive ? 'text-stone-900' : 'text-stone-400'}`} />
                  {item.label}
                </button>
              </li>
            );
          })}
        </ul>
      </nav>
      <div className="p-4 border-t border-stone-100 text-xs text-stone-400">
        Generated by Canvas<br/>GLM 4.7 Research
      </div>
    </aside>
  );
};

export default Sidebar;